# Generated by Django 4.0.2 on 2022-05-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wireframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(max_length=200)),
                ('project_file', models.TextField(max_length=200)),
                ('project_password', models.TextField()),
                ('project_uid', models.CharField(max_length=200)),
            ],
        ),
    ]
