# Generated by Django 4.0.2 on 2022-06-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wireframe_id', models.IntegerField(max_length=200)),
                ('Activity_name', models.CharField(max_length=200)),
                ('Component_id', models.IntegerField(max_length=200, null=True)),
            ],
        ),
    ]
