# Generated by Django 4.0.2 on 2022-06-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_component', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('wireframe_id', models.CharField(max_length=200)),
            ],
        ),
    ]
