# Generated by Django 4.0.2 on 2022-06-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_activty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wireframe_id', models.IntegerField()),
                ('activity_name', models.CharField(max_length=200)),
                ('component_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Activty',
        ),
    ]
