# Generated by Django 4.0.2 on 2022-06-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_component'),
        ('project', '0002_rules'),
    ]

    operations = [
    ]
