# Generated by Django 4.0.2 on 2022-06-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_activity_delete_activty'),
        ('project', '0003_merge_0002_component_0002_rules'),
    ]

    operations = [
    ]
