# Generated by Django 4.0.2 on 2022-06-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_context_context_conjunction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wireframe',
            name='project_us_purpose',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wireframe',
            name='project_us_todo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wireframe',
            name='project_us_user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
