# Generated by Django 4.0.2 on 2022-06-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_wireframe_project_us_purpose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_title', models.CharField(max_length=200)),
                ('wireframe_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='context',
            name='scenario_id',
            field=models.IntegerField(null=True),
        ),
    ]
