# Generated by Django 4.0.2 on 2022-06-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_scenario_context_scenario_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
        migrations.RemoveField(
            model_name='context',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='context',
            name='context_conjunction',
        ),
        migrations.RemoveField(
            model_name='context',
            name='rule_id',
        ),
        migrations.RemoveField(
            model_name='context',
            name='wireframe_id',
        ),
        migrations.AddField(
            model_name='context',
            name='context_template',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
