# Generated by Django 4.0.2 on 2022-06-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_delete_activity_delete_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='inner',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
